# Generated by Django 4.2.23 on 2026-03-31 17:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academico', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300)),
                ('autor', models.CharField(max_length=300)),
                ('anio', models.PositiveIntegerField()),
                ('posgrado', models.CharField(max_length=200)),
                ('instituto', models.CharField(max_length=300)),
                ('area_conocimiento', models.CharField(max_length=200)),
                ('linea_investigacion', models.CharField(max_length=200)),
                ('resumen', models.TextField()),
                ('palabras_clave', models.CharField(help_text='Separadas por comas', max_length=300)),
                ('archivo_pdf', models.FileField(upload_to='materiales/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.programa')),
            ],
        ),
    ]
