# Generated by Django 4.2.23 on 2026-01-28 03:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academico', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('archivo_pdf', models.FileField(upload_to='materiales/')),
                ('autor', models.CharField(max_length=200)),
                ('anio', models.PositiveIntegerField()),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.programa')),
            ],
            options={
                'verbose_name': 'Material Académico',
                'verbose_name_plural': 'Materiales Académicos',
            },
        ),
    ]
